// Generated by GitHub Copilot
// Reads window.PROFILE from data/profile.js and renders the full page.

(function () {
  'use strict';

  const P = window.PROFILE;
  if (!P) { console.error('PROFILE data not loaded. Check data/profile.js'); return; }

  /* ─── Helpers ──────────────────────────────────────────────── */

  /**
   * Creates an HTML element with optional class names and inner HTML.
   * @param {string} tag
   * @param {string|string[]} [cls]
   * @param {string} [html]
   * @returns {HTMLElement}
   */
  function el(tag, cls, html) {
    const node = document.createElement(tag);
    if (cls) node.className = Array.isArray(cls) ? cls.join(' ') : cls;
    if (html !== undefined) node.innerHTML = html;
    return node;
  }

  /**
   * Builds a section wrapper with divider, icon, and heading.
   * @param {string} id        - section id attribute
   * @param {string} iconEmoji
   * @param {string} iconColor - CSS class e.g. 'icon-blue'
   * @param {string} titleHTML - heading innerHTML
   * @returns {{ section: HTMLElement, body: HTMLElement }}
   */
  function buildSection(id, iconEmoji, iconColor, titleHTML) {
    const section = el('section', 'section reveal');
    section.id = id;
    section.setAttribute('aria-labelledby', id + '-title');

    const hr = el('hr', 'divider');
    section.appendChild(hr);

    const header = el('div', 'section-header');
    header.style.marginTop = '2.5rem';

    const icon = el('div', ['section-icon', iconColor]);
    icon.setAttribute('aria-hidden', 'true');
    icon.textContent = iconEmoji;
    header.appendChild(icon);

    const title = el('h2', 'section-title');
    title.id = id + '-title';
    title.innerHTML = titleHTML;
    header.appendChild(title);

    section.appendChild(header);

    const body = el('div');
    section.appendChild(body);

    return { section, body };
  }

  /* ─── Nav ──────────────────────────────────────────────────── */
  function renderNav() {
    const initials = P.name.first[0] + P.name.last[0];
    document.querySelector('.nav-logo').innerHTML = `${initials}<span>.</span>`;
  }

  /* ─── Hero ─────────────────────────────────────────────────── */
  function renderHero() {
    const hero = document.getElementById('hero');

    // Name
    document.getElementById('hero-name').innerHTML =
      `${P.name.first}<br><span>${P.name.last}</span>`;

    // Tags (role chips)
    const tagsWrap = document.getElementById('hero-tags');
    tagsWrap.innerHTML = '';
    [P.name.first.split(' ')[0] + ' ' + P.name.last, ...P.taglines.slice(0, 3)]
      .slice(0, 4)
      .forEach(t => {
        const s = el('span', 'tag', t);
        tagsWrap.appendChild(s);
      });

    // CTA buttons
    document.getElementById('hero-email-btn').href = `mailto:${P.email}`;
    if (P.github) {
      const ghBtn = document.getElementById('hero-github-btn');
      if (ghBtn) ghBtn.href = P.github;
    }

    // Stats
    const statsWrap = document.getElementById('hero-stats-wrap');
    statsWrap.innerHTML = '';
    P.stats.forEach(s => {
      const stat = el('div', 'stat');
      const num  = el('div', 'stat-num', s.animated ? '0' : String(s.value));
      num.id = s.id;
      const label = el('div', 'stat-label', s.label);
      stat.appendChild(num);
      stat.appendChild(label);
      statsWrap.appendChild(stat);
    });
  }

  /* ─── About ────────────────────────────────────────────────── */
  function renderAbout(container) {
    const card = el('div', 'about-card');
    card.innerHTML =
      P.about +
      `<br><br>📍 ${P.location} &nbsp;|&nbsp; 🌐 ${P.languages.join(' &amp; ')}`;
    container.appendChild(card);
  }

  /* ─── Skills ───────────────────────────────────────────────── */
  function renderSkills(container) {
    const grid = el('div', 'skills-grid');
    P.skills.forEach(group => {
      const card = el('article', 'skill-card');
      card.appendChild(el('h3', 'skill-card-title', group.category));
      const pills = el('div', 'skill-pills');
      group.items.forEach(item => {
        const pill = el('span', item.highlight ? 'skill-pill highlight' : 'skill-pill', item.name);
        pills.appendChild(pill);
      });
      card.appendChild(pills);
      grid.appendChild(card);
    });
    container.appendChild(grid);
  }

  /* ─── Experience ───────────────────────────────────────────── */
  function renderExperience(container) {
    const timeline = el('div', 'timeline');
    timeline.setAttribute('role', 'list');

    P.experience.forEach(job => {
      const item = el('article', 'tl-item');
      item.setAttribute('role', 'listitem');

      const dot = el('div', job.dotColor === 'green' ? 'tl-dot green' : 'tl-dot');
      dot.setAttribute('aria-hidden', 'true');
      item.appendChild(dot);

      const card = el('div', 'tl-card');

      const header = el('div', 'tl-header');
      header.appendChild(el('h3', 'tl-role', job.role));
      header.appendChild(el('span', 'tl-date', job.period));
      card.appendChild(header);

      card.appendChild(el('div', 'tl-company', job.company));

      const ul = el('ul', 'tl-bullets');
      ul.setAttribute('aria-label', 'Responsibilities');
      job.bullets.forEach(b => {
        ul.appendChild(el('li', null, b));
      });
      card.appendChild(ul);

      item.appendChild(card);
      timeline.appendChild(item);
    });

    container.appendChild(timeline);
  }

  /* ─── Projects ─────────────────────────────────────────────── */
  function renderProjects(container) {
    const grid = el('div', 'projects-grid');

    P.projects.forEach(proj => {
      const card = el('article', 'project-card');

      const top = el('div', 'project-top');
      const icon = el('div', 'project-icon');
      icon.setAttribute('aria-hidden', 'true');
      icon.textContent = proj.icon;
      top.appendChild(icon);
      if (proj.award) {
        const award = el('span', 'project-award');
        award.setAttribute('aria-label', 'Award: ' + proj.award.replace(/[^\w\s]/g, '').trim());
        award.innerHTML = proj.award;
        top.appendChild(award);
      }
      card.appendChild(top);

      const meta = el('div');
      meta.appendChild(el('h3', 'project-title', proj.title));
      meta.appendChild(el('div', 'project-org',  proj.org));
      meta.appendChild(el('div', 'project-date', proj.date));
      card.appendChild(meta);

      card.appendChild(el('p', 'project-desc', proj.description));

      if (proj.tech && proj.tech.length) {
        const tech = el('div', 'project-tech');
        tech.setAttribute('aria-label', 'Technologies used');
        proj.tech.forEach(t => tech.appendChild(el('span', 'skill-pill', t)));
        card.appendChild(tech);
      }

      grid.appendChild(card);
    });

    container.appendChild(grid);
  }

  /* ─── Education ────────────────────────────────────────────── */
  function renderEducation(container) {
    P.education.forEach(edu => {
      const card = el('div', 'edu-card');

      const icon = el('div', 'edu-icon');
      icon.setAttribute('aria-hidden', 'true');
      icon.textContent = edu.icon;
      card.appendChild(icon);

      const info = el('div');
      info.appendChild(el('h3', 'edu-degree', edu.degree));
      info.appendChild(el('div', 'edu-school', edu.school));
      info.appendChild(el('div', 'edu-dates',  edu.period));

      const badges = el('div', 'edu-badges');
      edu.badges.forEach(b => {
        badges.appendChild(el('span', b.gold ? 'edu-badge gold' : 'edu-badge', b.text));
      });
      info.appendChild(badges);
      card.appendChild(info);

      container.appendChild(card);
    });
  }

  /* ─── Certifications ───────────────────────────────────────── */
  function renderCertifications(container) {
    const grid = el('div', 'cert-grid');
    P.certifications.forEach(cert => {
      const card = el('article', 'cert-card');

      const badge = el('div', 'cert-badge');
      badge.style.background = cert.color;
      badge.setAttribute('aria-hidden', 'true');
      badge.textContent = cert.icon;
      card.appendChild(badge);

      const info = el('div', 'cert-info');
      info.appendChild(el('div', 'cert-code',   cert.code));
      info.appendChild(el('div', 'cert-name',   cert.name));
      info.appendChild(el('div', 'cert-issuer', cert.issuer));
      card.appendChild(info);

      grid.appendChild(card);
    });
    container.appendChild(grid);
  }

  /* ─── Awards ───────────────────────────────────────────────── */
  function renderAwards(container) {
    const grid = el('div', 'awards-grid');
    P.awards.forEach(award => {
      const card = el('div', 'award-card');

      const icon = el('span', 'award-icon');
      icon.setAttribute('aria-hidden', 'true');
      icon.textContent = award.icon;
      card.appendChild(icon);

      const info = el('div');
      info.appendChild(el('div', 'award-name', award.name));
      info.appendChild(el('div', 'award-year', award.year));
      card.appendChild(info);

      grid.appendChild(card);
    });
    container.appendChild(grid);
  }

  /* ─── Contact ──────────────────────────────────────────────── */
  function renderContact(container) {
    const bar = el('div', 'contact-bar');
    bar.appendChild(el('p', null, 'Open to collaborations, opportunities, and interesting conversations.'));

    const links = el('div', 'contact-links');

    const emailChip = el('a', 'contact-chip');
    emailChip.href = `mailto:${P.email}`;
    emailChip.innerHTML = `<span aria-hidden="true">✉️</span> ${P.email}`;
    links.appendChild(emailChip);

    const phoneChip = el('a', 'contact-chip');
    phoneChip.href = `tel:${P.phoneE164}`;
    phoneChip.innerHTML = `<span aria-hidden="true">📱</span> ${P.phone}`;
    links.appendChild(phoneChip);

    const locChip = el('span', 'contact-chip');
    locChip.innerHTML = `<span aria-hidden="true">📍</span> ${P.location}`;
    links.appendChild(locChip);

    if (P.github) {
      const ghChip = el('a', 'contact-chip');
      ghChip.href = P.github;
      ghChip.target = '_blank';
      ghChip.rel = 'noopener noreferrer';
      ghChip.innerHTML = `<span aria-hidden="true">🐙</span> ${P.github.replace('https://', '')}`;
      links.appendChild(ghChip);
    }

    bar.appendChild(links);
    container.appendChild(bar);
  }

  /* ─── Build All Sections ───────────────────────────────────── */
  function buildSections() {
    const main = document.getElementById('main-content');

    const defs = [
      { id: 'about',         emoji: '👤', color: 'icon-blue',   title: 'About <span>Me</span>',                fn: renderAbout         },
      { id: 'skills',        emoji: '⚡', color: 'icon-green',  title: 'Skills &amp; <span>Expertise</span>',  fn: renderSkills        },
      { id: 'experience',    emoji: '💼', color: 'icon-purple', title: 'Professional <span>Experience</span>', fn: renderExperience    },
      { id: 'projects',      emoji: '🚀', color: 'icon-orange', title: 'Featured <span>Projects</span>',       fn: renderProjects      },
      { id: 'education',     emoji: '🎓', color: 'icon-purple', title: '<span>Education</span>',               fn: renderEducation     },
      { id: 'certifications',emoji: '📜', color: 'icon-yellow', title: '<span>Certifications</span>',          fn: renderCertifications},
      { id: 'awards',        emoji: '🏆', color: 'icon-yellow', title: '<span>Awards &amp; Activities</span>', fn: renderAwards        },
      { id: 'contact',       emoji: '📬', color: 'icon-blue',   title: 'Get in <span>Touch</span>',            fn: renderContact       }
    ];

    defs.forEach(def => {
      const { section, body } = buildSection(def.id, def.emoji, def.color, def.title);
      def.fn(body);
      main.appendChild(section);
    });
  }

  /* ─── Interactions ─────────────────────────────────────────── */

  /** Theme toggle — persists in localStorage. */
  function initTheme() {
    const btn  = document.getElementById('theme-toggle');
    const root = document.documentElement;
    const saved = localStorage.getItem('theme') || 'dark';
    root.setAttribute('data-theme', saved);
    btn.textContent = saved === 'dark' ? '☀️ Light' : '🌙 Dark';

    btn.addEventListener('click', () => {
      const next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', next);
      localStorage.setItem('theme', next);
      btn.textContent = next === 'dark' ? '☀️ Light' : '🌙 Dark';
    });
  }

  /** Mobile hamburger nav. */
  function initMobileNav() {
    const toggle = document.getElementById('nav-toggle');
    const links  = document.getElementById('nav-links');
    toggle.addEventListener('click', () => {
      const open = links.classList.toggle('open');
      toggle.setAttribute('aria-expanded', String(open));
    });
    links.querySelectorAll('a').forEach(a => {
      a.addEventListener('click', () => {
        links.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
      });
    });
    document.addEventListener('keydown', e => {
      if (e.key === 'Escape' && links.classList.contains('open')) {
        links.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
        toggle.focus();
      }
    });
  }

  /** Typewriter cycling through PROFILE.taglines. */
  function initTypewriter() {
    const tw = document.getElementById('typewriter');
    if (!tw) return;
    let pi = 0, ci = 0, deleting = false;
    function tick() {
      const phrase = P.taglines[pi];
      tw.textContent = deleting ? phrase.slice(0, --ci) : phrase.slice(0, ++ci);
      if (!deleting && ci === phrase.length) { deleting = true; setTimeout(tick, 1800); return; }
      if (deleting && ci === 0)             { deleting = false; pi = (pi + 1) % P.taglines.length; }
      setTimeout(tick, deleting ? 55 : 80);
    }
    tick();
  }

  /** Animate a numeric counter from 0 to target. */
  function animateCounter(el, target) {
    let cur = 0;
    const step  = Math.ceil(target / 40);
    const timer = setInterval(() => {
      cur = Math.min(cur + step, target);
      el.textContent = cur;
      if (cur >= target) clearInterval(timer);
    }, 40);
  }

  /** Scroll-reveal + counter trigger using IntersectionObserver. */
  function initScrollReveal() {
    let countersStarted = false;
    const io = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (!entry.isIntersecting) return;
        entry.target.classList.add('visible');
        io.unobserve(entry.target);
        if (!countersStarted) {
          countersStarted = true;
          P.stats.forEach(s => {
            if (s.animated) {
              const node = document.getElementById(s.id);
              if (node) animateCounter(node, Number(s.value));
            }
          });
        }
      });
    }, { threshold: 0.15 });
    document.querySelectorAll('.reveal').forEach(el => io.observe(el));
  }

  /** Highlight active nav link based on scroll position. */
  function initActiveNav() {
    const anchors = document.querySelectorAll('.nav-links a');
    const io = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (!entry.isIntersecting) return;
        anchors.forEach(a => {
          const active = a.getAttribute('href') === '#' + entry.target.id;
          a.style.color = active ? 'var(--accent)' : '';
          active ? a.setAttribute('aria-current', 'page')
                 : a.removeAttribute('aria-current');
        });
      });
    }, { rootMargin: '-40% 0px -55% 0px' });
    document.querySelectorAll('section[id]').forEach(s => io.observe(s));
  }

  /* ─── Page Title & Footer Year ─────────────────────────────── */
  function initMeta() {
    document.title = `${P.name.first} ${P.name.last} | Software Engineer & Data AI Specialist`;
    const yearEl = document.getElementById('year');
    if (yearEl) yearEl.textContent = new Date().getFullYear();
  }

  /* ─── Bootstrap ────────────────────────────────────────────── */
  function init() {
    renderNav();
    renderHero();
    buildSections();
    initTheme();
    initMobileNav();
    initTypewriter();
    initScrollReveal();
    initActiveNav();
    initMeta();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
